<a href="https://colab.research.google.com/github/MujeebDawar/2-D-Convolution-Phyton/blob/main/2D_Convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Implementing 2-D Convolution from Scratch**


> By Mujeeb ur Rehman

> Semester 1 (MS-CGD)


**Technologies:** Python, NumPy

This notebook presents an implementation of the 2-D convolution operation developed from scratch using NumPy.

 all variables are square matrices, and the size
 of the kernel matrix can also be an even number.

# 1. Import Statements

In [1]:
import numpy as np

# 2. 2-D Convolution Implementation

In [35]:
#Perform the 2-D convolution operation.
def conv2d(input_matrix, kernel_matrix):
  #:input_matrix: the input matrix.
  #:kernel_matrix: the kernel matrix used for convolution.

  # Check none of the inputs are empty.
  if input_matrix.size == 0 or kernel_matrix.size == 0:
    raise Exception("Error! Empty matrices found.")
    return [[]] #return none

    # Check the input is a square matrix.
  if input_matrix.shape[0] != input_matrix.shape[1]:
    raise Exception("Error! The input is not a square matrix.")
    return [[]]#return none

    # Check also for the kernel is a square matrix.
  if kernel_matrix.shape[0] != kernel_matrix.shape[1]:
    raise Exception("Error! The kernel is not a square matrix.")
    return [[]]#return none

# Get the size of the input Matrix and kernel Matrix.
  input_size = input_matrix.shape[0]
  kernel_size = kernel_matrix.shape[0]

  # Check the kernel is not larger than the input matrix.
  if input_size < kernel_size:
    raise Exception("Error! The kernel is larger than the input.")
    return [[]]#return none

    # Flip the kernel.
  kernel_matrix = np.flip(kernel_matrix)

   # Set up size of the output matrix.
   #formula is M=n-k+1 where n is inputSize of Matrix and k is Input size of Kernal
  output_size = (input_size - kernel_size) + 1

  #setup outPut Matrix
  #The numpy.zeros() function returns a new array of given shape and type, with zeros.
  # Syntax:numpy.zeros(shape, dtype = None, order = 'C')
   #shape : integer or sequence of integers
   #order  : C_contiguous or F_contiguous
        # C-contiguous order in memory(last index varies the fastest)
        # C order means that operating row-rise on the array will be slightly quicker
        # FORTRAN-contiguous order in memory (first index varies the fastest).
        # F order means that column-wise operations will be faster.
#dtype : [optional, float(byDeafult)] Data type of returned array.

  output_mat = np.zeros(shape = (output_size, output_size), dtype=int)
  row_offset = 0

  for output_row in range(output_size):
    col_offset = 0

    for output_col in range(output_size):
      kernel_row = 0

      for row in range(row_offset, row_offset + kernel_size):
        kernel_col = 0

        for col in range(col_offset, col_offset + kernel_size):

          # Perform the convolution computation.
          output_mat[output_row, output_col] += (kernel_matrix[kernel_row, kernel_col] * input_matrix[row, col])
          kernel_col += 1

        kernel_row += 1

      col_offset += 1

    row_offset += 1

  return output_mat

# 3. Test Cases

3.1. Test Case #1

**After defining the conv2d() function, it can now be tested with some given test cases.**

In [38]:
# Define the input matrix.
input_matrix = np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]])

# Define the matrix kernel.
kernel_matrix = np.array([[1, 0],
                       [0, 1]])



In [39]:
output_mat = conv2d(input_matrix, kernel_matrix)
print(output_mat)

[[2 4 2]
 [4 2 4]
 [2 4 2]]


**3.2. Test Case #2**

In [42]:
# Define the input matrix.
input_mat = np.array([[3, 0, 0, 0],
                      [0, 3, 0, 0],
                      [0, 0, 3, 0],
                      [0, 0, 0, 3]])

# Define the matrix kernel.
kernel_mat = np.array([[1, 0],
                       [0, 1]])


In [43]:
output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[6 0 0]
 [0 6 0]
 [0 0 6]]


**3.3. Test Case #3**


Here, we can see that the function can work with negative numbers.

In [44]:
# Define the input matrix.
input_mat = np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])

# Define the matrix kernel.
kernel_mat = np.array([[1, -1],
                       [-1, 0]])

In [45]:
output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]


**3.4. Test Case #4**

Here, it is ensured that the function works if the input and the kernel matrices are the same.

In [46]:
# Define the input matrix.
input_mat = np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])

# Define the matrix kernel.
kernel_mat = np.array([[1, 0, 0, 0],
                       [0, 1, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]])

In [47]:
output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[4]]


**3.5. Test Case #5**

This test case presents the case where the kernel is larger than the input matrix. In this case, the functions prints an error.

In [48]:
# Define the input matrix.
input_mat = np.array([[1, -1],
                      [-1, 0]])

# Define the matrix kernel.
kernel_mat = np.array([[1, 0, 0, 0],
                       [0, 1, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]])


In [49]:
output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)


Exception: Error! The kernel is larger than the input.